### ISSUE TITLE
样式很乱

### ISSUE THREAD

**Issue by william-xue** [zhangzheng1019/Angular-webApp#9]
我帮你改改算了

**Comment by zhangzheng1019** [comment]
那个文件样式不行？

**Comment by zhangzheng1019** [comment]
@william-xue 哪个样式文件不行？

**Comment by william-xue** [comment]
TypeError: Cannot read property 'positionClass' of undefined
你今天又更改了什么

**Comment by zhangzheng1019** [comment]
@william-xue 你运行遇到这个问题TypeError: Cannot read property 'positionClass' of undefined？
把搜索版块写完了，
